#!/usr/bin/env bash
# 공개 Flutter/RN 저장소의 Swift·Objective-C 쪽 브리지 사실을 cartograph bridges 로 센다.
# 인덱스는 루트의 더미 패키지로만 만든다. USR 은 붙지 않지만 사실과 한계는 전부 나온다.
set -uo pipefail
ROOT="${SCAN_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/cartograph-scan.XXXXXX")}"; echo "scan root: $ROOT"
WORK="$ROOT/repos"; OUT="$ROOT/out"; mkdir -p "$WORK" "$OUT"
BIN="${CARTOGRAPH:-$(command -v cartograph)}"
REPOS=(
  fluttercommunity/plus_plugins
  flutter/packages
  Baseflow/flutter-permission-handler
  Baseflow/flutter-geolocator
  juliansteenbakker/flutter_secure_storage
  juliansteenbakker/mobile_scanner
  bluefireteam/audioplayers
  ryanheise/just_audio
  firebase/flutterfire
  tekartik/sqflite
  MaikuB/flutter_local_notifications
  react-native-webview/react-native-webview
  react-native-device-info/react-native-device-info
  mrousavy/react-native-vision-camera
)
for repo in "${REPOS[@]}"; do
  name="${repo//\//__}"; dir="$WORK/$name"
  if [ ! -d "$dir" ]; then
    git clone -q --depth 1 --filter=blob:none "https://github.com/$repo.git" "$dir" 2>>"$OUT/clone.err" || { echo "clone failed: $repo"; continue; }
  fi
  sha="$(git -C "$dir" rev-parse HEAD)"
  # 더미 패키지: 인덱스 스토어를 만들기 위한 것. 저장소에 루트 Package.swift 가 있으면 건드리지 않는다.
  if [ ! -f "$dir/Package.swift" ]; then
    mkdir -p "$dir/.cartograph-scan/Sources/ScanIndex"
    echo 'let scanIndex = 0' > "$dir/.cartograph-scan/Sources/ScanIndex/ScanIndex.swift"
    cat > "$dir/Package.swift" <<'PKG'
// swift-tools-version: 5.9
import PackageDescription
let package = Package(name: "CartographScanIndex", targets: [.target(name: "ScanIndex", path: ".cartograph-scan/Sources/ScanIndex")])
PKG
  fi
  (cd "$dir" && swift build > /dev/null 2>"$OUT/$name.build.err") || echo "build failed: $repo"
  "$BIN" bridges --project "$dir" --format json > "$OUT/$name.json" 2>"$OUT/$name.err"; rc=$?
  swift_files=$(find "$dir" -name "*.swift" -not -path "*/.build/*" -not -path "*/.cartograph-scan/*" -not -path "*/example/*" | wc -l | tr -d ' ')
  m_files=$(find "$dir" \( -name "*.m" -o -name "*.mm" \) -not -path "*/example/*" | wc -l | tr -d ' ')
  pigeon_files=$(grep -rlE "Autogenerated from Pigeon|pigeon" --include="*.swift" "$dir" 2>/dev/null | grep -v example | wc -l | tr -d ' ')
  echo "{\"repo\":\"$repo\",\"sha\":\"$sha\",\"rc\":$rc,\"swiftFiles\":$swift_files,\"objcFiles\":$m_files,\"pigeonSwiftFiles\":$pigeon_files}" > "$OUT/$name.meta.json"
  echo "$repo rc=$rc swift=$swift_files objc=$m_files pigeon=$pigeon_files"
done
