#!/usr/bin/env bash
# 공개 Flutter/RN 저장소의 Swift·Objective-C 쪽 브리지 사실을 cartograph bridges 로 센다.
# 인덱스는 루트의 더미 패키지로만 만든다. USR 은 붙지 않지만 사실과 한계는 전부 나온다.
#
# 재현: 저장소마다 커밋을 고정한다(`owner/repo@sha`). 고정이 없으면 그날의 HEAD 를 받고
# 기록만 남긴다 — 그 결과는 스냅샷이지 재현 가능한 측정이 아니다.
# `example/` 은 파일 수와 사실 양쪽에서 뺀다. 예제 앱의 등록은 플러그인의 사실이 아니다.
set -uo pipefail
ROOT="${SCAN_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/cartograph-scan.XXXXXX")}"; echo "scan root: $ROOT"
WORK="$ROOT/repos"; OUT="$ROOT/out"; mkdir -p "$WORK" "$OUT"
BIN="${CARTOGRAPH:-$(command -v cartograph)}"
REPOS=(
  fluttercommunity/plus_plugins@13e170479b3c66c890fa401f5fdb3af141faf67a
  flutter/packages@a929c2fc2d3660ae0e37f459f6ab3e0ed6db7553
  Baseflow/flutter-permission-handler@fc60b52afbd076d90f25ee950952cbd434e88595
  Baseflow/flutter-geolocator@209f35634ec7616cf822f8854a109b1f7782941a
  juliansteenbakker/flutter_secure_storage@e144260cb3c05166d0db4322a46b4637e042351c
  juliansteenbakker/mobile_scanner@997502afa588d4ee6a497d4f50919e9a5628707c
  bluefireteam/audioplayers@cd475c760b2e730c4306c1f102f3ac6f4313109e
  ryanheise/just_audio@454a24cac1c39442009f9e18ceccceac8e53d4a8
  firebase/flutterfire@7a5c2950e2731c25b150b57a7007c08f240e3b9b
  tekartik/sqflite@263864b51650c9d64b569de5bf48d45f73245aec
  MaikuB/flutter_local_notifications@b475bc883dab07da3c1b19e86b0746eb20f14f2f
  react-native-webview/react-native-webview@d65a961080dad3e82d33370ad6e8d90e973fcbd3
  react-native-device-info/react-native-device-info@06a9ed6d700cab9c55b363e6fa944ee8e5605745
  mrousavy/react-native-vision-camera@91bae1f08d549b50444ee16661dc4f4375cba0b6
)
CARTOGRAPH_SHA="$(git -C "$(dirname "$0")/.." rev-parse --short HEAD 2>/dev/null || echo unknown)"
echo "cartograph $("$BIN" --version) @ $CARTOGRAPH_SHA"
for entry in "${REPOS[@]}"; do
  repo="${entry%%@*}"; pin="${entry#*@}"; [ "$pin" = "$entry" ] && pin=""
  name="${repo//\//__}"; dir="$WORK/$name"
  if [ ! -d "$dir" ]; then
    if [ -n "$pin" ]; then
      git init -q "$dir" && git -C "$dir" remote add origin "https://github.com/$repo.git" \
        && git -C "$dir" fetch -q --depth 1 --filter=blob:none origin "$pin" 2>>"$OUT/clone.err" \
        && git -C "$dir" checkout -q FETCH_HEAD 2>>"$OUT/clone.err" || { echo "fetch failed: $entry"; continue; }
    else
      git clone -q --depth 1 --filter=blob:none "https://github.com/$repo.git" "$dir" 2>>"$OUT/clone.err" || { echo "clone failed: $repo"; continue; }
    fi
  fi
  sha="$(git -C "$dir" rev-parse HEAD)"
  # 더미 패키지: 인덱스 스토어를 만들기 위한 것. 저장소에 루트 Package.swift 가 있으면 건드리지 않는다.
  if [ ! -f "$dir/Package.swift" ]; then
    mkdir -p "$dir/.cartograph-scan/Sources/ScanIndex"
    echo 'let scanIndex = 0' > "$dir/.cartograph-scan/Sources/ScanIndex/ScanIndex.swift"
    cat > "$dir/Package.swift" <<'PKG'
// swift-tools-version: 5.9
import PackageDescription
let package = Package(name: "CartographScanIndex", targets: [.target(name: "ScanIndex", path: ".cartograph-scan/Sources/ScanIndex")])
PKG
  fi
  (cd "$dir" && swift build > /dev/null 2>"$OUT/$name.build.err") || echo "build failed: $repo"
  "$BIN" bridges --project "$dir" --format json --exclude '**/example/**' '**/.cartograph-scan/**' > "$OUT/$name.json" 2>"$OUT/$name.err"; rc=$?
  swift_files=$(find "$dir" -name "*.swift" -not -path "*/.build/*" -not -path "*/.cartograph-scan/*" -not -path "*/example/*" | wc -l | tr -d ' ')
  m_files=$(find "$dir" \( -name "*.m" -o -name "*.mm" \) -not -path "*/example/*" | wc -l | tr -d ' ')
  # Pigeon 산출물의 생성기 헤더 문구를 파일 어디서든 찾는다. 인용문이 있으면 과계수될 수 있다.
  pigeon_files=$(grep -rl "Autogenerated from Pigeon" --include="*.swift" "$dir" 2>/dev/null | grep -v "/example/" | wc -l | tr -d ' ')
  echo "{\"repo\":\"$repo\",\"sha\":\"$sha\",\"rc\":$rc,\"cartographSha\":\"$CARTOGRAPH_SHA\",\"swiftFiles\":$swift_files,\"objcFiles\":$m_files,\"pigeonSwiftFiles\":$pigeon_files}" > "$OUT/$name.meta.json"
  echo "$repo rc=$rc swift=$swift_files objc=$m_files pigeon=$pigeon_files"
done
